# docker-compose.yml
version: '3.8'
volumes:
  orderdb_vol:

networks:
  micro_network:
    external:
      name: micro_network

services:
  order-api:
    container_name: corder-service
    build:
      context: .
    ports:
    - "5003:5003"
    depends_on:
      - order-db
    networks:
      - micro_network
    restart: always

  order-db:
    container_name: corder_dbase
    image: nouchka/sqlite3
    #ports:
    #- "32002:3306"
    #environment:
    #  MYSQL_ROOT_PASSWORD:
    #  MYSQL_DATABASE:
    #  MYSQL_USER:
    #  MYSQL_PASSWORD:
    networks:
      - micro_network
    volumes:
    - orderdb_vol:/var/lib/sqlite3